services:
  toxiproxy:
    image: shopify/toxiproxy
    platform: linux/amd64
    container_name: toxiproxy
    ports:
      - "8474:8474"
      - "18080:18080"
    networks:
      - swim-cluster

  swim-node1:
    build: .
    container_name: swim-node1
    ports:
      - "8080:8080"
    environment:
      SWIM_ID: swim-node1
      SWIM_SEEDS: swim-node1=swim-node1:8080,swim-node2=swim-node2:8080,swim-node3=toxiproxy:18080
    volumes:
      - /var/log/swim
    networks:
      - swim-cluster

  swim-node2:
    build: .
    container_name: swim-node2
    ports:
      - "8081:8080"
    environment:
      SWIM_ID: swim-node2
      SWIM_SEEDS: swim-node1=swim-node1:8080,swim-node2=swim-node2:8080,swim-node3=swim-node3:8080
    volumes:
      - /var/log/swim
    networks:
      - swim-cluster

  swim-node3:
    build: .
    container_name: swim-node3
    ports:
      - "8082:8080"
    environment:
      SWIM_ID: swim-node3
      SWIM_SEEDS: swim-node1=swim-node1:8080,swim-node2=swim-node2:8080,swim-node3=swim-node3:8080
    volumes:
      - /var/log/swim
    networks:
      - swim-cluster

networks:
  swim-cluster:
    driver: bridge